add Link to A component
nwplus/livesite pull request #127
Opened 2020-11-25 18:26 UTC by stephaniejnc

issue #82 
- becomes a Link if color and weight are passed
- waiting on nwTheme.colors.primary to be changed

2020-11-26 07:14 UTC, stephaniejnc commented
- note that for hackcampTheme, primary is the same as linkHover color in ThemeProvider
- for hacker app link, just pass color and weight into regular A component, otherwise pass nothing

![nwTheme](https://user-images.githubusercontent.com/3856856/100318606-29904f80-2f73-11eb-94f1-4bd66f52f0ec.gif)
![hackcampTheme](https://user-images.githubusercontent.com/3856856/100318890-a7545b00-2f73-11eb-96db-0ec7b11ce157.gif)

2020-11-26 23:49 UTC, panjenny0 requested changes
Good job! Left some comments to make the component as reusable as possible :)

2020-11-26 23:49 UTC, panjenny0 commented on src/pages/Charcuterie.js
> +        <A color={false} weight={false} href="https://nwplus.io">
```suggestion
        <A href="https://nwplus.io">
```

2020-11-26 23:49 UTC, panjenny0 commented on src/components/Typography.js
> +  font-weight: ${p => (p.weight ? 600 : 400)};
I think this property should be named `bolded` to represent how it styles the text
```suggestion
  font-weight: ${p => (p.bolded ? 600 : 400)};
```

2020-11-26 23:49 UTC, panjenny0 commented on src/pages/Charcuterie.js
> +        <A color={true} weight={true} href="https://nwplus.io">
```suggestion
        <A color="primary" bolded href="https://nwplus.io">
```

2020-11-26 23:49 UTC, panjenny0 commented on src/components/Typography.js
> +  color: ${p => (p.color ? p.theme.colors.primary : p.theme.colors.link)};
Just to make this component as reusable as possible, can we make it something like this?
```suggestion
  color: ${p => (p.color ? p.color === "primary" && p.theme.colors.primary || p.color : p.theme.colors.link)};
```

2020-11-27 22:08 UTC, stephaniejnc commented
thank you so much @panjenny0 :))

2020-11-27 23:08 UTC, panjenny0 commented on src/components/Typography.js
> +  color: ${p => (p.color ? p.color === "primary" && p.theme.colors.primary || p.color : p.theme.colors.link)};
lol I think my suggestion caused a linting error :angrycry:
can you add a bracket here?
```suggestion
  color: ${p => (p.color ? (p.color === "primary" && p.theme.colors.primary) || p.color : p.theme.colors.link)};
```

2020-11-28 00:50 UTC, panjenny0 approved these changes
good stuff!! :shipit:

2020-11-28 03:54 UTC, merged