Add sponsors to confirmation page
nwplus/livesite pull request #175
Opened 2020-12-03 10:51 UTC by michelleykim

I am so sorry if there is a specific format I need to follow when making a pull request.. I just did whatever....

## Change Summary

> Sponsor logos added to the application confirmation page, due to the tight timeline, logos are hard coded rather than fetched from backend.

## Screenshots

<img width="1445" alt="confirmation page" src="https://user-images.githubusercontent.com/33190160/101000100-a9da2600-351a-11eb-9d5d-624da681e0a3.PNG">

Closes #132

2020-12-04 05:35 UTC, panjenny0 requested changes
Added some comments to make the sponsor logos more responsive
<img width="489" alt="Screen Shot 2020-12-03 at 9 31 00 PM" src="https://user-images.githubusercontent.com/38872354/101125767-de97bd00-35ae-11eb-9998-c989d6c33588.png">
I know the rest of the content including the social media logos are not mobile responsive yet but @acchiang will help us with this in #155 :)

2020-12-04 05:35 UTC, panjenny0 commented on src/containers/Landing/Footer.js
> +  justify-content: center;
```suggestion
  width: 100%;
  margin-top: 38em;
  display: block;
  text-align: center;
  justify-content: center;
  align-items: center;
```

2020-12-04 05:35 UTC, panjenny0 commented on src/containers/Landing/Footer.js
> +  top: 2.5em;
```suggestion
  z-index: 100;
  display: flex;
  flex-wrap: wrap;
  align-items: center;
  justify-content: center;
  margin: 24px 0;
  top: 2.5em;
```

2020-12-04 05:35 UTC, panjenny0 commented on src/containers/Landing/Footer.js
> +  margin: 32px;
```suggestion
  margin: 16px 32px;
```

2020-12-04 07:30 UTC, panjenny0 approved these changes
lgtm! 
why does your diff contain so many past commits 😆

2020-12-05 00:59 UTC, acchiang commented
> lgtm!
> why does your diff contain so many past commits 😆

maybe she rebased master on top of her branch instead of merging it into her branch hahahaha

2020-12-06 03:57 UTC, ianmah requested changes
Could you remove `package-lock.json` (We are using yarn)
Also if you can try to fix the commit history lool not sure if merging master into this branch will fix it?

2020-12-08 03:51 UTC, panjenny0 approved these changes

2020-12-11 01:46 UTC, ianmah approved these changes

2020-12-11 01:47 UTC, merged