fix: leaf clipping + scrollbar
nwplus/livesite pull request #278
Opened 2021-02-27 19:00 UTC by jackyzha0

2021-02-27 20:12 UTC, jvssicawu requested changes

2021-02-27 20:12 UTC, jvssicawu commented on src/pages/Home.js
>  const TopDecal = styled(Decal)`
can we change the 275px in left: and width: on lines 19 and 21 to 265px so that one lilypad isn't floating in space hehe

2021-02-28 06:18 UTC, jvssicawu commented
LOL jacky u r gonna hate this but the nested scrollbar came back, I think u have to hide the overflow in the parent div of the decal :sweats:

2021-02-28 17:05 UTC, jackyzha0 commented
> LOL jacky u r gonna hate this but the nested scrollbar came back, I think u have to hide the overflow in the parent div of the decal :sweats:

the parent div of the decal is the whole page :mildpanic:

2021-03-02 23:27 UTC, ianmah reviewed
Quicklinks arent clickable for me on the homepage. (1080p monitor)

2021-03-02 23:27 UTC, ianmah commented
![image](https://user-images.githubusercontent.com/11839441/109728816-c9113f80-7b6b-11eb-94c2-4c729a192567.png)
maybe we can add a background colour to these so the dotted lines dont show?

2021-03-02 23:29 UTC, ianmah commented
Not sure if because of this PR but i dont see a spinner when i click show spinner on charcuterie

2021-03-02 23:51 UTC, jvssicawu approved these changes
lgtm :))

2021-03-02 23:52 UTC, merged